### ISSUE TITLE
Can I use this readonly in online games?

### ISSUE THREAD

**Issue by SpoinkyNL** [Bakkes/BakkesModSDK#1]
Hello,

I'm working on an [application](https://github.com/SpoinkyNL/Artemis) that shows game data on RGB keyboards and I was wondering if it's possible to read current score, player boost etc. while in online games?

**Comment by Bakkes** [comment]
Hey, unfortunately not. I've thought about it but I decided to make it so it can't work online (even read only). The problem is: Psyonix has said they don't want mods interacting with online play, and even though it doesn't hinder the other players, I'm afraid the SDK will be used to create tools that create an unfair advantage if I allow users to even read the game data (like custom DirectX overlay and stuff)

**Comment by SpoinkyNL** [comment]
I see, fair enough. Thanks anyway and good luck with development :)
